# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180818_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mode_a',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mode_b',
        ),
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('cop', 'Cash on Pickup'), ('ppd', 'PayPal on Delivery'), ('ppp', 'PayPal on Pickup')], default='cod', max_length=10),
        ),
    ]
